<a href="https://colab.research.google.com/github/scan33scan33/data-science-class/blob/master/colabs/Example_0_Tables_and_Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Python 0-d ~ 4-d arrays
table_0d = 0
table_1d = [0]
table_2d = [[0]]
table_3d = [[[0]]]
table_4d = [[[[0]]]]

print(table_0d)
print(table_1d)
print(table_2d)


0
[0]
[[0]]


In [2]:
# Commonly seen tables
list_of_1d_examples = [[1, 1], [0, 0], [1, 0]] # e.g. examples of vectorized features.
list_of_2d_examples = [[[0, 2], [1, 0]], [[1, 1], [1, 1]]] # e.g. examples of grey-scale images
# ... this applies to higher dimensions.

In [3]:
# Convert to numpy arrays
import numpy as np
array_of_1d_examples = np.array(list_of_1d_examples)
array_of_2d_examples = np.array(list_of_2d_examples)
print(list_of_2d_examples)
print(array_of_2d_examples)

[[[0, 2], [1, 0]], [[1, 1], [1, 1]]]
[[[0 2]
  [1 0]]

 [[1 1]
  [1 1]]]


In [15]:
### Some useful numpy array operations...
# Slicing features.
print ('original:\n', array_of_2d_examples[:])
print ('first example:\n', array_of_2d_examples[0])
print ('a row of the first example:\n', array_of_2d_examples[0, 0, :])
print ('a row of the first example:\n', array_of_2d_examples[0, -1, :])
print ('rows of the first example:\n', array_of_2d_examples[0, [0, 1], :])
print ('a column of the first example:\n', array_of_2d_examples[0, :, 0])

original:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
first example:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a row(*) of the first example:
 [1 2 3 4]
a row(*) of the first example:
 [ 9 10 11 12]
a row(*) of the first example:
 [[1 2 3 4]
 [5 6 7 8]]
a column(*) of the first example:
 [1 5 9]


In [5]:
# Concatenations

print(array_of_1d_examples)
# np.hstack([array_of_1d_examples, [[0, 1]]])
print(np.concatenate([array_of_1d_examples, [[0, 1]], [[2, 1]]], axis=0))
# np.vstack
print(np.concatenate([array_of_1d_examples, [[4], [5], [6] ]], axis=1))

# A
# [[1 1]
# [0 0]
# [1 0]]
# B
# [[4]
#  [5]
#  [6]]

# concat([A B], axis=1)
# [ [1, 1] + [4],
# [ [0, 0] + [5],
# ...

[[1 1]
 [0 0]
 [1 0]]
[[1 1]
 [0 0]
 [1 0]
 [0 1]
 [2 1]]
[[1 1 4]
 [0 0 5]
 [1 0 6]]


In [6]:
# reshaping
import numpy as np
a = np.array([1, 2, 3])
print(a.reshape(3, 1))
print(a.reshape(-1, 1, 3))

[[1]
 [2]
 [3]]
[[[1 2 3]]]


In [7]:
# Reshape high-dimension arrays to low-dimension arrays
print(array_of_2d_examples)
print(array_of_2d_examples.reshape(2, 4))

[[[0 2]
  [1 0]]

 [[1 1]
  [1 1]]]
[[0 2 1 0]
 [1 1 1 1]]


In [8]:
# array-vs-array and array-vs-number operations.
print(array_of_1d_examples + 100)
# array_of_1d_examples = array_of_1d_examples + 100
print(array_of_1d_examples)
print(array_of_1d_examples / [[2], [0.0000000001], [1]])
print(array_of_1d_examples + array_of_1d_examples)



[[101 101]
 [100 100]
 [101 100]]
[[1 1]
 [0 0]
 [1 0]]
[[0.5 0.5]
 [0.  0. ]
 [1.  0. ]]
[[2 2]
 [0 0]
 [2 0]]


In [9]:
print(array_of_2d_examples)
# print(array_of_2d_examples / [[2], [3]])
print(array_of_2d_examples / [[[2], [3]], [[4], [5]]])

[[[0 2]
  [1 0]]

 [[1 1]
  [1 1]]]
[[[0.         1.        ]
  [0.33333333 0.        ]]

 [[0.25       0.25      ]
  [0.2        0.2       ]]]


In [10]:
# conditional updates
print(array_of_1d_examples == 1)
local_array = array_of_1d_examples.copy()
local_array[array_of_1d_examples == 1] = -1
print(local_array)
local_array2 = local_array
local_array2[0, 0] = 1
print(local_array[0, 0])

[[ True  True]
 [False False]
 [ True False]]
[[-1 -1]
 [ 0  0]
 [-1  0]]
1


In [11]:
# Some basic math functions just FYI.
# print(array_of_1d_examples.mean(axis=1))
# [[1 1], [0, 0]]
# axis = 0: a = [1, 1], b = [0, 0]
#           mean(a + b)
# axis = 1: {(1), (1)}, {(0), (0)}
# a0 = 1, b0 = 1, mean(a + b)
# a1 = 0, b1 = 0, mean(a + b)

print(array_of_2d_examples)
# print(array_of_2d_examples.mean(axis=0))
# a = [[0 2], [1 0]] 
# b = [[1 1], [1 1]]
# mean([a, b]) = a + b / 2
# print(array_of_2d_examples.mean(axis=1))
# [mean([0 2], [1 0]),
#  mean([1 1], [1 1])]
#[[[0 2]
# [1 0]]
#
# [[1 1]
#  [1 1]]]
# axis = 0
# mean([[[0 2]
#        [1 0]]
#      [[1 1]
#       [1 1]]])
#
#[mean([[0 2]
#      [1 0]],
# mean[[1 1]
#      [1 1]] )] 
#

#[[mean([0 2])
#  mean([1 0])]
#
# [mean([1 1])
#  [1 1]]]
# print(array_of_2d_examples)
# 2 x 3 x 4
array_of_2d_examples = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
                                 [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]])
print("original")
print(array_of_2d_examples.shape)
print("axis=0")
print(array_of_2d_examples.mean(axis=0).shape)
print("axis=1")
print(array_of_2d_examples.mean(axis=1).shape)
print("axis=2")
print(array_of_2d_examples.mean(axis=-1).shape)

# t \ signal  
# 1 [1.2, 3.4]
# 2 [3.2, 3.2]


[[[0 2]
  [1 0]]

 [[1 1]
  [1 1]]]
original
(2, 3, 4)
axis=0
(3, 4)
axis=1
(2, 4)
axis=2
(2, 3)


In [12]:
new_array_of_2d_examples = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                            [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
new_array_of_2d_examples = np.array(new_array_of_2d_examples)
#print(new_array_of_2d_examples.mean(axis=0)) # 2 element of 3 x 4
# avg([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
#     [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])
#print(new_array_of_2d_examples.mean(axis=1)) 
# [avg([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), # 3 elements of 4
#  avg([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])]
print(new_array_of_2d_examples.mean(axis=2))
# [([avg([1, 2, 3, 4]), [5, 6, 7, 8], [9, 10, 11, 12]]), # 3 elements of 4
#  ([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])]


[[ 2.5  6.5 10.5]
 [14.5 18.5 22.5]]


In [22]:
# Pandas DataFrame: data + metadata
import pandas as pd
import requests
result = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.c45-names')
def get_column_names(content):
  features = []
  for line in content.decode().split("\n"):
    parts = line.split(":")
    if len(parts) == 2: 
      features.append(parts[0])
  return features + ["classes"]
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data',
                 header=None,
                 names=get_column_names(result.content))
display('df:\n', df[:10])
print("type(df.keys) is ", type(df.keys))
print("type(df.values) is ", type(df.values))
print(df.values)

'df:\n'

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc
5  vhigh  vhigh     2       2      med   high   unacc
6  vhigh  vhigh     2       2      big    low   unacc
7  vhigh  vhigh     2       2      big    med   unacc
8  vhigh  vhigh     2       2      big   high   unacc
9  vhigh  vhigh     2       4    small    low   unacc

type(df.keys) is  <class 'method'>
type(df.values) is  <class 'numpy.ndarray'>
[['vhigh' 'vhigh' '2' ... 'small' 'low' 'unacc']
 ['vhigh' 'vhigh' '2' ... 'small' 'med' 'unacc']
 ['vhigh' 'vhigh' '2' ... 'small' 'high' 'unacc']
 ...
 ['low' 'low' '5more' ... 'big' 'low' 'unacc']
 ['low' 'low' '5more' ... 'big' 'med' 'good']
 ['low' 'low' '5more' ... 'big' 'high' 'vgood']]


In [24]:
# Convert data to numerical form for them to make sense
mapping = {'small': 1, 'med': 2, 'big': 3}
df = df.replace({'lug_boot': mapping})

display(df[:10])

  buying  maint doors persons  lug_boot safety classes
0  vhigh  vhigh     2       2         1    low   unacc
1  vhigh  vhigh     2       2         1    med   unacc
2  vhigh  vhigh     2       2         1   high   unacc
3  vhigh  vhigh     2       2         2    low   unacc
4  vhigh  vhigh     2       2         2    med   unacc
5  vhigh  vhigh     2       2         2   high   unacc
6  vhigh  vhigh     2       2         3    low   unacc
7  vhigh  vhigh     2       2         3    med   unacc
8  vhigh  vhigh     2       2         3   high   unacc
9  vhigh  vhigh     2       4         1    low   unacc


In [30]:
# Shuffle your data for better randomenss.
from sklearn.utils import shuffle
df = shuffle(df)
display(df[:10])

buying  maint  doors persons  lug_boot safety classes
457    high  vhigh      2    more         3    med   unacc
1466    low   high      4       2         3   high   unacc
120   vhigh   high      2       4         2    low   unacc
962     med  vhigh  5more       4         3   high     acc
563    high   high      2    more         2   high     acc
766    high    low      2       4         1    med   unacc
1416    low   high      2       4         2    low   unacc
341   vhigh    low      2       4         3   high     acc
290   vhigh    med      4    more         1   high     acc
474    high  vhigh      3       4         3    low   unacc

In [33]:
# Count numbers of cars with buying=high
print(df['buying'] == 'high')
print("# buying = high: ", len(df[df['buying'] == 'high']))

457      True
1466    False
120     False
962     False
563      True
        ...  
1603    False
721      True
1695    False
6       False
1001    False
Name: buying, Length: 1728, dtype: bool
# buying = high:  432


## In-class Exercises

In [29]:
# Q1: given the follow np.array,
a = np.array([[1.0, 2.0, 5.0], [2.0, 4.0, 5.0]])
# we can get the mean of all elements by the following code.
print(a.mean()) 
# how do we get the mean of each row? (expected answer: [2.66666667 3.66666667])
# YOUR ANSWER HERE

# Q1 advance: can you get the mean of each column?
# YOUR ANSWER HERE

# Q2: for each `buying` value, get the number of occurrence of this value in the table.
# YOUR ANSWER HERE


3.1666666666666665
[2.66666667 3.66666667]
